# Change these first
owner: tuxpeople # Your GitHub organization or username, where this repository lives
repo: monitoring # The name of this repository

sites:
  - name: Plex
    url: http://plex.eighty-three.me:32400/identity
  - name: Wallabag
    url: wallabag.eighty-three.me
  - name: Code Server
    url: code.eighty-three.me
  - name: Dokuwiki
    url: wiki.eighty-three.me
  - name: Gitea
    url: git.eighty-three.me
  - name: Gollum
    url: wiki2.eighty-three.me
  - name: Grafana
    url: grafana.eighty-three.me
  - name: Alertmanager
    url: alertmanager.eighty-three.me
  - name: Prometheus
    url: prometheus.eighty-three.me
  - name: Speedtest Plotter
    url: speed.eighty-three.me
  - name: Codimd
    url: codimd.eighty-three.me
  - name: Hasteserver
    url: paste.eighty-three.me
  - name: Sharry
    url: share.eighty-three.me

assignees: # Users to assign downtime issues (optional)
  - tuxpeople
  
status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: monitoring.eighty-three.me
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
