# Change these first
owner: tuxpeople # Your GitHub organization or username, where this repository lives
repo: monitoring # The name of this repository

sites:
  - name: Plex
    url: http://plex.eighty-three.me:32400/identity
  # - name: Wallabag
  #   url: https://wallabag.eighty-three.me
  # - name: Code Server
  #   url: https://code.eighty-three.me
  # - name: Grafana
  #   url: https://grafana.eighty-three.me
  # - name: Alertmanager
  #   url: https://alertmanager.eighty-three.me
  # - name: Prometheus
  #   url: https://prometheus.eighty-three.me
  # - name: Speedtest Plotter
  #   url: https://speed.eighty-three.me
  # - name: Codimd
  #   url: https://codimd.eighty-three.me
  # - name: Hasteserver
  #   url: https://paste.eighty-three.me

assignees: # Users to assign downtime issues (optional)
  - tuxpeople

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: monitoring.eighty-three.me
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "Status of some of my stuff"
  introMessage: "This is a test of [Upptime](https://github.com/upptime/upptime). The interesting thing about Upptime is: no server required — just GitHub Actions, Issues, and Pages."
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
